networks:
    ds218:
        external: true
        name: net_bridge
    macvlan:
        external: true
        name: net_macvlan

secrets:
    admin_token:
        file: ./vaultwarden/admin_token.sec
    database_url:
        file: ./vaultwarden/database_url.sec
    push_installation_id:
        file: ./vaultwarden/push_installation_id.sec
    push_installation_key:
        file: ./vaultwarden/push_installation_key.sec
    domain:
        file: ./vaultwarden/domain.sec
    signups_domains_whitelist:
        file: ./vaultwarden/signups_domains_whitelist.sec

services:

    vaultwarden:
        container_name: iserv-vaultwarden
        image: vaultwarden/server:latest
        networks:
            - ds218
            - macvlan
        volumes:
            - /volume1/docker/vaultwarden:/data:rw
            - ./env/resolv.conf:/etc/resolv.conf:ro
        environment:
            RSA_KEY_FILENAME: data/rsa_key
            ICON_CACHE_FOLDER: data/icon_cache
            ATTACHMENTS_FOLDER: data/attachments
            SENDS_FOLDER: data/sends
            TMP_FOLDER: data/tmp
            ROCKET_PORT: 8000
            USER: 1030:100
            #ADMIN_TOKEN: читать https://github.com/dani-garcia/vaultwarden/wiki/Enabling-admin-page
            #ADMIN_TOKEN: токен администратора
            ADMIN_TOKEN_FILE: /run/secrets/admin_token
            #https://github.com/dani-garcia/vaultwarden/wiki/Enabling-Mobile-Client-push-notification
            #Включение push-уведомлений мобильного клиента
            PUSH_ENABLED: true
            PUSH_INSTALLATION_ID_FILE: /run/secrets/push_installation_id
            PUSH_INSTALLATION_KEY_FILE: /run/secrets/push_installation_key
            #DATABASE_URL=mysql://[[user]:[password]@]host[:port][/database]
            DATABASE_URL_FILE: /run/secrets/database_url
            #DOMAIN: подставьте значение субдомена vaultwarden
            DOMAIN_FILE: /run/secrets/domain
            # Отключите эту опцию с помощью "false" после создания учетной записи, чтобы никто из посторонних не смог зарегистрироваться.
            SIGNUPS_ALLOWED: false
            #INVITATIONS_ALLOWED: false
            SIGNUPS_DOMAINS_WHITELIST_FILE: /run/secrets/signups_domains_whitelist
            #Отображение подсказки пароля
            #SHOW_PASSWORD_HINT:false
        secrets:
            - admin_token
            - database_url
            - push_installation_id
            - push_installation_key
            - domain
            - signups_domains_whitelist